const countryOptions = [
    { value: "AF", label: "Afghanistan", flag: "https://flagcdn.com/w40/af.png", code: "+93" },
    { value: "AL", label: "Albania", flag: "https://flagcdn.com/w40/al.png", code: "+355" },
    { value: "DZ", label: "Algeria", flag: "https://flagcdn.com/w40/dz.png", code: "+213" },
    { value: "AD", label: "Andorra", flag: "https://flagcdn.com/w40/ad.png", code: "+376" },
    { value: "AO", label: "Angola", flag: "https://flagcdn.com/w40/ao.png", code: "+244" },
    { value: "AR", label: "Argentina", flag: "https://flagcdn.com/w40/ar.png", code: "+54" },
    { value: "AM", label: "Armenia", flag: "https://flagcdn.com/w40/am.png", code: "+374" },
    { value: "AU", label: "Australia", flag: "https://flagcdn.com/w40/au.png", code: "+61" },
    { value: "AT", label: "Austria", flag: "https://flagcdn.com/w40/at.png", code: "+43" },
    { value: "AZ", label: "Azerbaijan", flag: "https://flagcdn.com/w40/az.png", code: "+994" },
    { value: "BS", label: "Bahamas", flag: "https://flagcdn.com/w40/bs.png", code: "+1-242" },
    { value: "BH", label: "Bahrain", flag: "https://flagcdn.com/w40/bh.png", code: "+973" },
    { value: "BD", label: "Bangladesh", flag: "https://flagcdn.com/w40/bd.png", code: "+880" },
    { value: "BB", label: "Barbados", flag: "https://flagcdn.com/w40/bb.png", code: "+1-246" },
    { value: "BY", label: "Belarus", flag: "https://flagcdn.com/w40/by.png", code: "+375" },
    { value: "BE", label: "Belgium", flag: "https://flagcdn.com/w40/be.png", code: "+32" },
    { value: "BZ", label: "Belize", flag: "https://flagcdn.com/w40/bz.png", code: "+501" },
    { value: "BJ", label: "Benin", flag: "https://flagcdn.com/w40/bj.png", code: "+229" },
    { value: "BT", label: "Bhutan", flag: "https://flagcdn.com/w40/bt.png", code: "+975" },
    { value: "BO", label: "Bolivia", flag: "https://flagcdn.com/w40/bo.png", code: "+591" },
    { value: "BA", label: "Bosnia and Herzegovina", flag: "https://flagcdn.com/w40/ba.png", code: "+387" },
    { value: "BW", label: "Botswana", flag: "https://flagcdn.com/w40/bw.png", code: "+267" },
    { value: "BR", label: "Brazil", flag: "https://flagcdn.com/w40/br.png", code: "+55" },
    { value: "BN", label: "Brunei", flag: "https://flagcdn.com/w40/bn.png", code: "+673" },
    { value: "BG", label: "Bulgaria", flag: "https://flagcdn.com/w40/bg.png", code: "+359" },
    { value: "BF", label: "Burkina Faso", flag: "https://flagcdn.com/w40/bf.png", code: "+226" },
    { value: "BI", label: "Burundi", flag: "https://flagcdn.com/w40/bi.png", code: "+257" },
    { value: "KH", label: "Cambodia", flag: "https://flagcdn.com/w40/kh.png", code: "+855" },
    { value: "CM", label: "Cameroon", flag: "https://flagcdn.com/w40/cm.png", code: "+237" },
    { value: "CA", label: "Canada", flag: "https://flagcdn.com/w40/ca.png", code: "+1" },
    { value: "CL", label: "Chile", flag: "https://flagcdn.com/w40/cl.png", code: "+56" },
    { value: "CN", label: "China", flag: "https://flagcdn.com/w40/cn.png", code: "+86" },
    { value: "CO", label: "Colombia", flag: "https://flagcdn.com/w40/co.png", code: "+57" },
    { value: "HR", label: "Croatia", flag: "https://flagcdn.com/w40/hr.png", code: "+385" },
    { value: "CU", label: "Cuba", flag: "https://flagcdn.com/w40/cu.png", code: "+53" },
    { value: "CY", label: "Cyprus", flag: "https://flagcdn.com/w40/cy.png", code: "+357" },
    { value: "CZ", label: "Czech Republic", flag: "https://flagcdn.com/w40/cz.png", code: "+420" },
    { value: "DK", label: "Denmark", flag: "https://flagcdn.com/w40/dk.png", code: "+45" },
    { value: "EG", label: "Egypt", flag: "https://flagcdn.com/w40/eg.png", code: "+20" },
    { value: "FI", label: "Finland", flag: "https://flagcdn.com/w40/fi.png", code: "+358" },
    { value: "FR", label: "France", flag: "https://flagcdn.com/w40/fr.png", code: "+33" },
    { value: "DE", label: "Germany", flag: "https://flagcdn.com/w40/de.png", code: "+49" },
    { value: "IN", label: "India", flag: "https://flagcdn.com/w40/in.png", code: "+91" },
    { value: "IT", label: "Italy", flag: "https://flagcdn.com/w40/it.png", code: "+39" },
    { value: "JP", label: "Japan", flag: "https://flagcdn.com/w40/jp.png", code: "+81" },
    { value: "MY", label: "Malaysia", flag: "https://flagcdn.com/w40/my.png", code: "+60" },
    { value: "MX", label: "Mexico", flag: "https://flagcdn.com/w40/mx.png", code: "+52" },
    { value: "NZ", label: "New Zealand", flag: "https://flagcdn.com/w40/nz.png", code: "+64" },
    { value: "RU", label: "Russia", flag: "https://flagcdn.com/w40/ru.png", code: "+7" },
    { value: "SA", label: "Saudi Arabia", flag: "https://flagcdn.com/w40/sa.png", code: "+966" },
    { value: "ZA", label: "South Africa", flag: "https://flagcdn.com/w40/za.png", code: "+27" },
    { value: "KR", label: "South Korea", flag: "https://flagcdn.com/w40/kr.png", code: "+82" },
    { value: "ES", label: "Spain", flag: "https://flagcdn.com/w40/es.png", code: "+34" },
    { value: "SE", label: "Sweden", flag: "https://flagcdn.com/w40/se.png", code: "+46" },
    { value: "CH", label: "Switzerland", flag: "https://flagcdn.com/w40/ch.png", code: "+41" },
    { value: "US", label: "United States", flag: "https://flagcdn.com/w40/us.png", code: "+1" },
    { value: "VN", label: "Vietnam", flag: "https://flagcdn.com/w40/vn.png", code: "+84" },
    { value: "ZW", label: "Zimbabwe", flag: "https://flagcdn.com/w40/zw.png", code: "+263" }
];

export default countryOptions;
