export const products = [
    {
      title: 'QRPay - Money Transfer with QR Code Full Solution',
      category: 'Full-Applications',
      isFeatured: true,
      imageUrl: 'https://s3.envato.com/files/563988173/inline.png',
      link: 'https://qrpay.agency',
      price: '$79.00',
      sales: '498 Sales',
      cartLink: 'https://codecanyon.net/checkout/from_item/46376528?license=regular',
      previewLink: 'https://qrpay.agency',
    },
    {
      title: 'XRemit - Remittance Money Transfer Full Solution',
      category: 'Full-Applications',
      isFeatured: true,
      imageUrl: 'https://s3.envato.com/files/556853978/XRemit.png',
      link: 'https://xremit.app',
      price: '$49.00',
      sales: '122 Sales',
      cartLink: 'https://codecanyon.net/checkout/from_item/48035206?license=regular',
      previewLink: 'https://xremit.app',
    },
    {
      title: 'CrypInvest - Cryptocurrency Investment Platform Full Solution',
      category: 'Full-Applications',
      isFeatured: true,
      imageUrl: 'https://s3.envato.com/files/556845182/CrypInvest.png',
      link: 'https://crypinvest.app',
      price: '$59.00',
      sales: '125 Sales',
      cartLink: 'https://codecanyon.net/checkout/from_item/47446877?license=regular',
      previewLink: 'https://crypinvest.app',
    },
  ];
  