export const product1 = [
    {
      image: "https://appdevs.net/_next/static/media/qrpay.20aa96fb.webp",
      title: "QRPay Pro",
      pricing: "Starting at $299",
      features: ["Website", "Admin Panel", "User App", "Agent App", "Merchant App", "WooCommerce"],
      link: "https://qrpay-pro.app/installation-plan",
    },
    {
      image: "https://appdevs.net/_next/static/media/payload.14f171ab.webp",
      title: "PayLoad",
      pricing: "Starting at $249",
      features: ["Website", "Admin Panel", "User App"],
      link: "https://pay-load.agency/installation-plan",
    },
    {
      image: "https://appdevs.net/_next/static/media/xtream.502fb2ac.webp",
      title: "XTream",
      pricing: "Starting at $199",
      features: ["Website", "Admin Panel", "User App"],
      link: "https://xtream.agency/installation-plan",
    },
    {
        image: "https://appdevs.net/_next/static/media/nfcpay.38ff37f3.webp",
        title: "NFCPay",
        pricing: "Starting at $299",
        features: ["Website", "Admin Panel", "User App"],
        link: "https://nfc-pay.app/installation-plan",
      },
      {
        image: "https://appdevs.net/_next/static/media/moneymate.b87a2702.webp",
        title: "MoneyMate",
        pricing: "Starting at $249",
        features: ["Website", "Admin Panel", "User App"],
        link: "https://money-mate.app/installation-plan",
      },
      {
        image: "https://appdevs.net/_next/static/media/qrpay.20aa96fb.webp",
        title: "QRPay",
        pricing: "Starting at $299",
        features: ["Website", "Admin Panel", "User App", "Agent App", "Merchant App", "WooCommerce"],
        link: "https://qrpay.agency/installation-plan",
      },
      {
        image: "https://appdevs.net/_next/static/media/stripcard.2cc343d3.webp",
        title: "StripCard",
        pricing: "Starting at $299",
        features: ["Website", "Admin Panel", "User App"],
        link: "https://stripcard.app/installation-plan",
      },
      {
        image: "https://appdevs.net/_next/static/media/xremit.32bd3e01.webp",
        title: "XRemit",
        pricing: "Starting at $249",
        features: ["Website", "Admin Panel", "User App", "Agent App"],
        link: "https://xremit.app/installation-plan",
      },
      {
        image: "https://appdevs.net/_next/static/media/crypinvest.30ffda30.webp",
        title: "CrypInvest",
        pricing: "Starting at $249",
        features: ["Website", "Admin Panel", "User App"],
        link: "https://crypinvest.app/installation-plan",
      },
      {
        image: "https://appdevs.net/_next/static/media/escroc.c46ddd98.webp",
        title: "Escroc",
        pricing: "Starting at $249",
        features: ["Website", "Admin Panel", "User App"],
        link: "https://escroc.app/installation-plan",
      },
      {
        image: "https://appdevs.net/_next/static/media/walletium.8417fd21.webp",
        title: "Walletium",
        pricing: "Starting at $249",
        features: ["Website", "Admin Panel", "User App"],
        link: "https://walletium.agency/installation-plan",
      },
      {
        image: "https://appdevs.net/_next/static/media/adchange.739f0259.webp",
        title: "adChange",
        pricing: "Starting at $249",
        features: ["Website", "Admin Panel", "User App"],
        link: "https://adchange.app/installation-plan",
      },
      {
        image: "https://appdevs.net/_next/static/media/paylink.07eb2c32.webp",
        title: "PayLink",
        pricing: "Starting at $249",
        features: ["Website", "Admin Panel", "User App"],
        link: "https://pay-link.app/installation-plan",
      },
      {
        image: "https://appdevs.net/_next/static/media/handiman.86665eb3.webp",
        title: "Handiman",
        pricing: "Starting at $249",
        features: ["Website", "Admin Panel", "User App", "Vendor App"],
        link: "https://handiman.app/installation-plan",
      },
      {
        image: "https://appdevs.net/_next/static/media/adcrypto.d6a6a59c.webp",
        title: "AdCrypto",
        pricing: "Starting at $249",
        features: ["Website", "Admin Panel", "User App"],
        link: "https://adcrypto.app/installation-plan",
      },
      {
        image: "https://appdevs.net/_next/static/media/adfund.55b668df.webp",
        title: "AdFund",
        pricing: "Starting at $249",
        features: ["Website", "Admin Panel", "User App"],
        link: "https://adfund.app/installation-plan",
      },
      {
        image: "https://appdevs.net/_next/static/media/adoctor.5574ce74.webp",
        title: "ADoctor",
        pricing: "Starting at $249",
        features: ["Website", "Admin Panel", "User App"],
        link: "https://adoctor.app/installation-plan",
      },
      {
        image: "https://appdevs.net/_next/static/media/adradio.f03fba89.webp",
        title: "AdRadio",
        pricing: "Starting at $249",
        features: ["Website", "Admin Panel", "User App"],
        link: "https://adradio.app/installation-plan",
      },
      {
        image: "https://appdevs.net/_next/static/media/esalon.157a63f7.webp",
        title: "eSalon",
        pricing: "Starting at $249",
        features: ["Website", "Admin Panel", "User App"],
        link: "https://e-salon.app/installation-plan",
      },
      {
        image: "https://appdevs.net/_next/static/media/mycoin.a5a90c1e.webp",
        title: "MyCoin",
        pricing: "Starting at $249",
        features: ["Website", "Admin Panel", "User App"],
        link: "https://my-coin.app/installation-plan",
      },

];
  