const solutionimg = [
  {
    image: "https://appdevs.net/_next/static/media/remittance.6985c065.webp",
    title: "Mobile Banking Solutions",
    description: "Seamless banking on-the-go with secure transactions and features.",
    link: "/solutions/mobile-banking-solutions",
    width: 'w-[239px]',
    height: 'h-[150px]',

  },
  {
    image: "https://appdevs.net/_next/static/media/mobileBanking.26967535.webp",
    title: "Remittance Solutions",
    description: "Fast and affordable international money transfers made easy.",
    link: "/solutions/remittance-solutions",
    width: 'w-[186px]',
    height: 'h-[150px]',

  },
  {
    image: "https://appdevs.net/_next/static/media/digitalWallet.6f01a52e.webp",
    title: "Digital Wallet Solutions",
    description: "Secure digital wallet for effortless payments and fund management.",
    link: "/solutions/digital-wallet-solutions",
    width: 'w-[171px]',
    height: 'h-[150px]',
  },
  {
    image: "https://appdevs.net/_next/static/media/paymentGateway.38f212fa.webp",
    title: "Payment Gateway Solutions",
    description: "Reliable payment processing for online transactions and businesses.",
    link: "/solutions/white-label-payment-gateway-solutions",
    width: 'w-[194px]',
    height: 'h-[150px]',
  },
  {
    image: "https://appdevs.net/_next/static/media/currencyExchange.b0e3cab5.webp",
    title: "Currency Exchange Solutions",
    description: "Real-time currency conversion for global transactions at competitive rates.",
    link: "/solutions/currency-exchange-software-solutions",
    width: 'w-[194px]',
    height: 'h-[150px]',
  },
  {
    image: "https://appdevs.net/_next/static/media/currencyExchange.b0e3cab5.webp",
    title: "Card Issuing Solution",
    description: "Custom card solutions tailored for businesses and brands.",
    link: "/solutions/card-issuing-solutions",
    width: 'w-[194px]',
    height: 'h-[150px]',
  },
  {
    image: "https://appdevs.net/_next/static/media/crowdFunding.a17ce315.webp",
    title: "Crowdfunding Solutions",
    description: "Effective platform for raising funds and supporting projects with ease.",
    link: "/solutions/crowdfunding-solutions",
    width: 'w-[156px]',
    height: 'h-[150px]',
  },
  {
    image: "https://appdevs.net/_next/static/media/currencyExchange.b0e3cab5.webp",
    title: "Investment Management Solutions",
    description: "Comprehensive tools for effective portfolio management and growth.",
    link: "/solutions/investment-management-solutions",
    width: 'w-[185px]',
    height: 'h-[150px]',
  },
  {
    image: "https://appdevs.net/_next/static/media/paymentGateway.38f212fa.webp",
    title: "Escrow Solutions",
    description: "Secure transactions with trusted escrow services for peace of mind.",
    link: "/solutions/escrow-solutions",
    width: 'w-[194px]',
    height: 'h-[150px]',
  },
  {
    image: "https://appdevs.net/_next/static/media/digitalWallet.6f01a52e.webp",
    title: "AI Chatbot Solutions",
    description: "Comprehensive tools for effective portfolio management and growth.",
    link: "/solutions/ai-chatbot-solutions",
    width: 'w-[171px]',
    height: 'h-[150px]',
  },
  {
    image: "https://appdevs.net/_next/static/media/mobileBanking.26967535.webp",
    title: "Online Booking Solutions",
    description: "Comprehensive tools for effective portfolio management and growth.",
    link: "/solutions/online-booking-solutions",
    width: 'w-[186px]',
    height: 'h-[150px]',
  },
  {
    image: "https://appdevs.net/_next/static/media/remittance.6985c065.webp",
    title: "Multi-vendor Solutions",
    description: "Flexible platform for multiple sellers to showcase and sell products.",
    link: "/solutions/multi-vendor-solutions",
    width: 'w-[239px]',
    height: 'h-[150px]',
  },
];

export default solutionimg;
