export const technologies = [
    { name: "Next.js", imgSrc: "https://appdevs.net/_next/static/media/next.e4718ede.png" },
    { name: "React.js", imgSrc: "https://appdevs.net/_next/static/media/react.904540dc.png" },
    { name: "Vue.js", imgSrc: "https://appdevs.net/_next/static/media/vue.aff7846a.png" },
    { name: "HTML 5", imgSrc: "https://appdevs.net/_next/static/media/html.31928e1e.png" },
    { name: "CSS 3", imgSrc: "https://appdevs.net/_next/static/media/css.dec0a7fd.png" },
    { name: "Javascript", imgSrc: "https://appdevs.net/_next/static/media/javaScript.050d31a8.png" },
    { name: "TypeScript", imgSrc: "https://appdevs.net/_next/static/media/typescript.dffd2523.png" },
    { name: "Tailwind CSS", imgSrc: "https://appdevs.net/_next/static/media/tailwind.c0defc1b.png" },
    { name: "Bootstrap 5", imgSrc: "https://appdevs.net/_next/static/media/bootstrap.07490c77.png" },
    { name: "Material UI", imgSrc: "https://appdevs.net/_next/static/media/material.00527df5.png" },
    { name: "Ant Design", imgSrc: "https://appdevs.net/_next/static/media/antdesign.78de393c.png" },
    { name: "Laravel", imgSrc: "https://appdevs.net/_next/static/media/laravel.1e75d119.png" },
    { name: "Node.js", imgSrc: "https://appdevs.net/_next/static/media/node.cdcd21a2.png" },
    { name: "Django", imgSrc: "https://appdevs.net/_next/static/media/django.de93d1fa.png" },
    { name: "PHP", imgSrc: "https://appdevs.net/_next/static/media/php.b35ad523.png" },
    { name: "JWT", imgSrc: "https://appdevs.net/_next/static/media/jwt.44fde85b.png" },
    { name: "OAuth", imgSrc: "https://appdevs.net/_next/static/media/oauth.ea68040f.png" },
    { name: "Passport", imgSrc: "https://appdevs.net/_next/static/media/passport.200356e4.png" },
    { name: "QAuth", imgSrc: "https://appdevs.net/_next/static/media/autho.f1334aca.png" },
    { name: "Flutter", imgSrc: "https://appdevs.net/_next/static/media/flutter.1105ff90.png" },
    { name: "React Native", imgSrc: "https://appdevs.net/_next/static/media/native.9c7d1cdb.png" },
    { name: "Swift", imgSrc: "https://appdevs.net/_next/static/media/swift.0d26f8e6.png" },
    { name: "Kotlin", imgSrc: "https://appdevs.net/_next/static/media/kotlin.3d84e6c9.png" },
    { name: "Java", imgSrc: "https://appdevs.net/_next/static/media/java.281cc265.png" },
    { name: "Nginx", imgSrc: "https://appdevs.net/_next/static/media/nginx.a49ecd7e.png" },
    { name: "Apache", imgSrc: "https://appdevs.net/_next/static/media/apache.fed2d627.png" },
    { name: "AWS", imgSrc: "https://appdevs.net/_next/static/media/aws.5529cf18.png" },
    { name: "DigitalOcean", imgSrc: "https://appdevs.net/_next/static/media/ocean.3a1880e8.png" },  
    { name: "Google Cloud Platform", imgSrc: "https://appdevs.net/_next/static/media/googlecloud.b68df73e.png" },  
    { name: "Azure", imgSrc: "https://appdevs.net/_next/static/media/azure.b0caa6dd.png" },  // Example: added Azure
    { name: "Docker", imgSrc: "https://appdevs.net/_next/static/media/docker.9b4c3b12.png" },  // Example: added Docker
    { name: "Kubernetes", imgSrc: "https://appdevs.net/_next/static/media/kubernetes.2bd1b8e8.png" },  // Example: added Kubernetes
    { name: "GitHub Actions", imgSrc: "https://appdevs.net/_next/static/media/githubactions.30786ffa.png" },  // Example: added GitHub Actions
];